/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hibernatebasic;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        String unitName = "SimpleUnit";
        EntityManagerFactory factory = Persistence.createEntityManagerFactory(unitName);
        System.out.println(new App().getGreeting());
    }
}
