/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hibernatebasic;

import hibernatebasic.model.Professor;
import org.junit.Before;
import org.junit.Test;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import static org.junit.Assert.assertTrue;

public class AppTest {
    private final static String UNIT_NAME = "SimpleUnit";
    private static EntityManagerFactory EM_FACTORY;

    @Before
    public void init() {
        EM_FACTORY = Persistence.createEntityManagerFactory(UNIT_NAME);
    }

    @Test
    public void shouldOpenEmFactory() {
        assertTrue(EM_FACTORY.isOpen());
    }

    @Test
    public void shouldPersistEntity() {
        EntityManager em = EM_FACTORY.createEntityManager();
        em.getTransaction().begin();
        Professor entity = new Professor("John", "Doe");
        em.persist(entity);
        em.getTransaction().commit();
        em.close();
    }
}
