/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import app.model.Account;
import app.model.Student;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import java.util.List;

public class AppTest {
    private EntityManagerFactory entityManagerFactory;
    private EntityManager em;

    @Before
    public void init() {
        entityManagerFactory = Persistence.createEntityManagerFactory("SimpleUnit");
        em = entityManagerFactory.createEntityManager();
    }

    @After
    public void destroy() {
        em.close();
        entityManagerFactory.close();
    }

    @Test
    public void shouldPersistEntity() {
        Account acc = new Account(); // 1. New (transient)
        acc.setName("John89");
        Student student = new Student();
        student.setName("John");
        student.setAccount(acc);
        em.persist(acc); // 2. Persisted
        // 3. Commit Transaction
        em.getTransaction().begin();
        em.getTransaction().commit();
        // 4. JPQL
        TypedQuery<Student> studentQuery;
        studentQuery = em.createQuery("SELECT s FROM Student s", Student.class);
        List<Student> resultList = studentQuery.getResultList();
        Assert.assertEquals(1, resultList.size());
    }



}
